/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 chairDraco.gltf --transform
Author: SforsaVge (https://sketchfab.com/SforsaVge)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-chair-e6127170f3844df499941ebdf7c8a4b4
Title: Gaming Chair
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/chairDraco-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-8.67, 8.37, -5.47]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[4.73, 4.86, 4.86]}
      >
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-2.62, 3.34, -5.93]}
        rotation={[1.38, 0, 0]}
        scale={[3.33, 4.87, 5.2]}
      >
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group
        position={[-8.04, 0.33, 0.3]}
        rotation={[-0.21, 0, 0]}
        scale={[0.63, 4.64, 3.35]}
      >
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group
        position={[2.66, 0.31, 0.19]}
        rotation={[-0.21, 0, 0]}
        scale={[-0.63, 4.64, 3.35]}
      >
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[-2.62, -2.14, -1.33]} scale={[0.94, 0.56, 0.94]}>
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group
        position={[-7.58, -7.3, -1.14]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.3, 0.16, 0.3]}
      >
        <group position={[0, 0, 0.27]}>
          <mesh
            geometry={nodes.Object_29.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_31.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_33.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group
          position={[15.65, -1.09, -4.33]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[2.25, 1.17, 1.17]}
        >
          <mesh
            geometry={nodes.Object_35.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group
        position={[2.33, -7.3, -1.51]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.3, 0.16, 0.3]}
      >
        <group position={[0, 0, 0.27]}>
          <mesh
            geometry={nodes.Object_40.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_41.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_43.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_44.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group
          position={[15.65, -1.09, -4.33]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[2.25, 1.17, 1.17]}
        >
          <mesh
            geometry={nodes.Object_46.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_47.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group
        position={[-2.78, -7.15, -6.23]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.3, 0.16, 0.3]}
      >
        <group position={[0, 0, 0.27]}>
          <mesh
            geometry={nodes.Object_51.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_52.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_53.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_54.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_55.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group
          position={[15.65, -1.09, -4.33]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[2.25, 1.17, 1.17]}
        >
          <mesh
            geometry={nodes.Object_57.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_58.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          geometry={nodes.Object_49.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group
        position={[-2.45, -7.15, 3.47]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.3, 0.16, 0.3]}
      >
        <group position={[0, 0, 0.27]}>
          <mesh
            geometry={nodes.Object_62.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_63.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_64.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_65.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_66.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group
          position={[15.65, -1.09, -4.33]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[2.25, 1.17, 1.17]}
        >
          <mesh
            geometry={nodes.Object_68.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Object_69.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          geometry={nodes.Object_60.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[-2.62, -0.05, -3.84]} scale={[2.34, 1.72, 0.86]}>
        <mesh
          geometry={nodes.Object_71.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_72.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-2.73, 8.8, -6.32]} scale={[2.04, 1.39, 0.97]}>
        <mesh
          geometry={nodes.Object_74.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_75.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials["Material.003"]}
        position={[3.03, -2.13, -0.66]}
        scale={[-0.47, 4.3, 4.3]}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials["Material.003"]}
        position={[-2.62, -2.17, -1.32]}
        scale={[1.21, 0.56, 1.21]}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials["Material.004"]}
        position={[-8.38, -2.18, -0.68]}
        scale={[0.47, 4.3, 4.3]}
      />
    </group>
  );
}

useGLTF.preload("/chairDraco-transformed.glb");
